#!/bin/bash

function constructor
{
    constructor="$(realpath "$0" | xargs dirname)"
}

function constructor_permission
{
    if [ "$(id -u)" -ne 0 ]
    then
        echo "Error: Cannot execute the constructor without permission."
        exit 1
    fi
}

function constructor_package
{
    constructor_package="$constructor/constructor-package"

    if [ ! -d "$constructor_package" ]
    then
        echo "Error: Cannot read the constructor package."
        exit 1
    fi
}

function constructor_toolchain
{
    constructor_toolchain="$constructor/constructor-toolchain"

    if [ ! -d "$constructor_toolchain" ]
    then
        echo "Error: Cannot read the constructor toolchain."
        exit 1
    fi
}

function toolchain_archive
{
    toolchain_archive="$constructor_toolchain/toolchain/archive/toolchain.tar.gz"

    if [ ! -f "$toolchain_archive" ]
    then
        echo "Error: Cannot read the toolchain archive."
        exit 1
    fi
}

function toolchain_root
{
    toolchain_root="$constructor/toolchain-root/$package"

    if [ ! -d "$toolchain_root" ]
    then
        mkdir --parents "$toolchain_root"

        if ! tar                        \
            --extract                   \
            --file "$toolchain_archive" \
            --directory "$toolchain_root"
        then
            echo "Error: Cannot extract the toolchain archive."
            exit 1
        fi
    fi
}

function toolchain_constructor
{
    toolchain_constructor="$toolchain_root/constructor"

    if [ ! -d "$toolchain_constructor" ]
    then
        if ! cp --recursive "$constructor_package" "$toolchain_constructor"
        then
            echo "Error: Cannot copy the toolchain constructor."
            exit 1
        fi
    fi
}

function toolchain_owner
{
    toolchain_owner="root"

    if ! chown --recursive                  \
        "$toolchain_owner:$toolchain_owner" \
        "$toolchain_root"
    then
        echo "Error: Cannot change the toolchain owner."
        exit 1
    fi
}

function toolchain_mount
{
    toolchain_mount="$toolchain_root/$1"

    if [ ! -d "$toolchain_mount" ]
    then
        mkdir "$toolchain_mount"
    fi

    toolchain_mount_type="$2"

    if ! mount --types          \
        "$toolchain_mount_type" \
        "$toolchain_mount_type" \
        "$toolchain_mount"
    then
        echo "Error: Cannot mount the toolchain."
        exit 1
    fi
}

function toolchain_bind
{
    toolchain_bind="$toolchain_constructor/package/$1"

    if [ ! -d "$toolchain_bind" ]
    then
        mkdir "$toolchain_bind"
    fi

    toolchain_bind_source="$constructor_package/package/$1"

    if [ ! -d "$toolchain_bind_source" ]
    then
        mkdir "$toolchain_bind_source"
    fi

    if ! mount --bind            \
        "$toolchain_bind_source" \
        "$toolchain_bind"
    then
        echo "Error: Cannot bind the toolchain."
        exit 1
    fi
}

function toolchain_chroot
{
    chroot "$toolchain_root"            \
        env --ignore-environment        \
            "HOME"="/root"              \
            "PATH"="/usr/bin:/usr/sbin" \
            "TERM"="$TERM"              \
            "MAKEFLAGS"="-j 4"          \
        bash "/constructor/constructor" "$package"
}

function toolchain_umount
{
    toolchain_umount="$toolchain_root/$1"

    if ! umount "$toolchain_umount"
    then
        echo "Error: Cannot umount the toolchain filesystem."
    fi
}

function main
{
    package="$@"

    if [ -z "$package" ]
    then
        echo "Usage: $(basename "$0") <package>"
    else
        constructor
        constructor_permission
        constructor_package
        constructor_toolchain

        toolchain_archive
        toolchain_root
        toolchain_constructor
        toolchain_owner

        toolchain_mount "/dev"         "devtmpfs"
        toolchain_mount "/dev/pts"     "devpts"
        toolchain_mount "/proc"        "proc"
        toolchain_mount "/sys"         "sysfs"
        toolchain_mount "/run"         "tmpfs"
        toolchain_mount "/tmp"         "tmpfs"

        toolchain_bind "build-archive"
        toolchain_bind "source-archive"

        toolchain_chroot

        toolchain_umount "/constructor/package/build-archive"
        toolchain_umount "/constructor/package/source-archive"
        toolchain_umount "/tmp"
        toolchain_umount "/run"
        toolchain_umount "/sys"
        toolchain_umount "/proc"
        toolchain_umount "/dev/pts"
        toolchain_umount "/dev"
    fi
}

main "$@"
